<a href="https://colab.research.google.com/github/dsmohiit/Machine-Learning-Repo/blob/main/PCA_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [116]:
import numpy as np
import pandas as pd

In [117]:
mean_vec1 = np.array([0, 0, 0])
cov_vec1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

class_1_sample = np.random.multivariate_normal(mean_vec1, cov_vec1, 20)

In [118]:
class_1_sample

array([[-1.61631565e+00,  3.75664046e-01,  2.94786346e-01],
       [-8.02495046e-01,  1.09195961e+00,  1.88832643e+00],
       [ 4.29752870e-01,  3.57577025e-01,  2.91652563e-01],
       [ 6.95294033e-01,  7.39983967e-02, -4.65082687e-01],
       [-7.64384657e-01, -8.70480210e-01,  4.40242167e-01],
       [ 6.91736456e-01, -2.36284784e-01, -2.64085993e+00],
       [-1.44426643e+00, -3.27188131e-01, -8.36708779e-04],
       [-1.26658092e-02,  3.37049771e-01, -6.47384818e-03],
       [ 2.42755784e-01, -7.91686722e-01,  1.39244103e+00],
       [ 3.38122124e-01,  2.58787351e-01, -1.34873538e+00],
       [-1.14890132e+00,  1.50133722e+00, -1.23445838e+00],
       [ 3.39575864e-01, -1.51094062e-02,  2.36975677e+00],
       [-7.85212696e-01,  5.43194884e-01,  3.96059592e-01],
       [ 4.74980846e-01, -7.83823585e-02, -6.98535096e-01],
       [-9.01179962e-01, -3.50119145e-01,  1.54916494e-01],
       [-1.04890216e-02,  1.33542607e+00, -7.65869583e-01],
       [-1.87558594e+00, -8.11697960e-01

In [119]:
df = pd.DataFrame(class_1_sample, columns= ["feature1", "feature2", "feature3"])
df["target"] = 1

In [120]:
df

feature1  feature2  feature3  target
0  -1.616316  0.375664  0.294786       1
1  -0.802495  1.091960  1.888326       1
2   0.429753  0.357577  0.291653       1
3   0.695294  0.073998 -0.465083       1
4  -0.764385 -0.870480  0.440242       1
5   0.691736 -0.236285 -2.640860       1
6  -1.444266 -0.327188 -0.000837       1
7  -0.012666  0.337050 -0.006474       1
8   0.242756 -0.791687  1.392441       1
9   0.338122  0.258787 -1.348735       1
10 -1.148901  1.501337 -1.234458       1
11  0.339576 -0.015109  2.369757       1
12 -0.785213  0.543195  0.396060       1
13  0.474981 -0.078382 -0.698535       1
14 -0.901180 -0.350119  0.154916       1
15 -0.010489  1.335426 -0.765870       1
16 -1.875586 -0.811698 -1.085656       1
17 -0.076014 -1.605291  0.234868       1
18  0.538493  0.478987  0.313541       1
19 -0.521476  0.624385 -0.529286       1

In [121]:
mean_vec2 = np.array([0, 0, 0])
cov_vec2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

class_2_sample = np.random.multivariate_normal(mean_vec2, cov_vec2, 20)

In [122]:
class_2_sample

array([[ 0.40133111,  0.1263126 ,  0.00906409],
       [ 0.67384015, -0.85355992,  0.60500162],
       [-1.81886418,  1.43363182,  0.79825014],
       [-0.52697287,  0.12413695, -0.75962662],
       [ 0.00885146,  0.00215015,  0.33480112],
       [ 1.18633082, -2.07115075,  0.93682964],
       [ 1.23616064, -0.03895668, -0.74404937],
       [ 0.38946395,  1.26220469,  0.02834681],
       [-0.54929411, -0.14972672, -0.7559722 ],
       [ 0.62837054, -0.46025228, -1.87988931],
       [-0.29909982,  0.73719009,  1.19799109],
       [-0.86740714,  0.21592449,  0.15529828],
       [ 0.78606937, -0.29910226,  0.12566733],
       [-0.89339609,  0.62848506,  0.46891484],
       [ 0.04864434, -1.50435732,  0.96741128],
       [ 0.49719939,  0.08527129, -1.44402782],
       [-0.40392846,  1.82558739,  1.02261899],
       [-0.26625448,  1.2828355 ,  0.43593617],
       [ 0.60224604,  0.21548308, -0.61547441],
       [-0.64746026, -0.61530788, -0.33895441]])

In [123]:
df2 = pd.DataFrame(class_2_sample, columns= ["feature1", "feature2", "feature3"])
df2["target"] = 0

In [124]:
df2

feature1  feature2  feature3  target
0   0.401331  0.126313  0.009064       0
1   0.673840 -0.853560  0.605002       0
2  -1.818864  1.433632  0.798250       0
3  -0.526973  0.124137 -0.759627       0
4   0.008851  0.002150  0.334801       0
5   1.186331 -2.071151  0.936830       0
6   1.236161 -0.038957 -0.744049       0
7   0.389464  1.262205  0.028347       0
8  -0.549294 -0.149727 -0.755972       0
9   0.628371 -0.460252 -1.879889       0
10 -0.299100  0.737190  1.197991       0
11 -0.867407  0.215924  0.155298       0
12  0.786069 -0.299102  0.125667       0
13 -0.893396  0.628485  0.468915       0
14  0.048644 -1.504357  0.967411       0
15  0.497199  0.085271 -1.444028       0
16 -0.403928  1.825587  1.022619       0
17 -0.266254  1.282836  0.435936       0
18  0.602246  0.215483 -0.615474       0
19 -0.647460 -0.615308 -0.338954       0

In [125]:
df = pd.concat([df1, df2], ignore_index= True)

In [126]:
df

feature1  feature2  feature3  target
0   0.071883  1.122578 -0.718635       1
1  -0.418385  0.557073 -0.221775       1
2  -0.169693  0.174837 -0.492055       1
3   2.193951 -1.329297  1.046259       1
4  -2.245727 -0.382813  1.002755       1
5  -0.533988 -1.698276 -1.294532       1
6   2.211553  0.007048  0.550223       1
7  -0.621581  0.139240  0.596562       1
8   0.256192 -1.238356  0.533091       1
9  -1.075662 -1.423762 -0.725545       1
10  0.534768  0.155419  0.509102       1
11 -2.167850 -0.096889  0.823299       1
12  0.520617 -0.195915 -0.115145       1
13  0.481053  1.196572  0.687791       1
14 -0.330632 -0.934112  1.941249       1
15 -1.583615  1.163063 -0.460694       1
16  1.399001  0.461988 -0.408911       1
17  1.791103 -0.588367 -0.480350       1
18 -0.192834 -0.244257 -1.631947       1
19  0.792922  0.614513  0.031201       1
20  0.401331  0.126313  0.009064       0
21  0.673840 -0.853560  0.605002       0
22 -1.818864  1.433632  0.798250       0
23 -0.526973  0.124137 -0.759627       0
24  0.008851  0.002150  0.334801       0
25  1.186331 -2.071151  0.936830       0
26  1.236161 -0.038957 -0.744049       0
27  0.389464  1.262205  0.028347       0
28 -0.549294 -0.149727 -0.755972       0
29  0.628371 -0.460252 -1.879889       0
30 -0.299100  0.737190  1.197991       0
31 -0.867407  0.215924  0.155298       0
32  0.786069 -0.299102  0.125667       0
33 -0.893396  0.628485  0.468915       0
34  0.048644 -1.504357  0.967411       0
35  0.497199  0.085271 -1.444028       0
36 -0.403928  1.825587  1.022619       0
37 -0.266254  1.282836  0.435936       0
38  0.602246  0.215483 -0.615474       0
39 -0.647460 -0.615308 -0.338954       0

In [127]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df.iloc[:, 0:3] = scaler.fit_transform(df.iloc[:, 0:3])

In [128]:
covariance_matrix = np.cov([df.iloc[:, 0],df.iloc[:, 1],df.iloc[:, 2]])

In [129]:
covariance_matrix

array([[ 1.02564103, -0.22223952, -0.09034465],
       [-0.22223952,  1.02564103,  0.02161296],
       [-0.09034465,  0.02161296,  1.02564103]])

In [130]:
eigen_value, eigen_vector = np.linalg.eig(covariance_matrix)

In [131]:
eigen_vector

array([[ 0.69460908, -0.71645295,  0.06491063],
       [-0.64936058, -0.66326818, -0.37202978],
       [-0.30959499, -0.21626486,  0.92594841]])

In [132]:
eigen_value

array([1.27367095, 0.79262813, 1.010624  ])

In [133]:
pc = eigen_vector[:2]

In [134]:
pc

array([[ 0.69460908, -0.71645295,  0.06491063],
       [-0.64936058, -0.66326818, -0.37202978]])

In [135]:
pc.shape

(2, 3)

In [136]:
df.iloc[:, 0:3].shape

(40, 3)

In [137]:
transformed_df = np.dot(df.iloc[:, 0:3], pc.T)

In [141]:
new_df = pd.DataFrame(transformed_df, columns= ["PC1", "PC2"])

In [143]:
new_df["target"] = df["target"].values

In [144]:
new_df

PC1       PC2  target
0  -0.934697 -0.528620       1
1  -0.777198 -0.022470       1
2  -0.325686  0.222141       1
3   2.588392 -0.844707       1
4  -1.168745  1.281462       1
5   0.857633  2.189220       1
6   1.497716 -1.620904       1
7  -0.518420  0.050825       1
8   1.166828  0.540064       1
9   0.317049  2.076568       1
10  0.243314 -0.652784       1
11 -1.357703  1.101105       1
12  0.465202 -0.107854       1
13 -0.608248 -1.465687       1
14  0.637025  0.061671       1
15 -2.065650  0.372893       1
16  0.512111 -1.017415       1
17  1.607965 -0.459080       1
18 -0.095833  1.051497       1
19  0.015172 -0.942267       1
20  0.137613 -0.325162       0
21  1.148192 -0.039356       0
22 -2.342615 -0.236562       0
23 -0.547454  0.603941       0
24 -0.003509 -0.130222       0
25  2.489791  0.387284       0
26  0.775044 -0.396540       0
27 -0.773455 -1.163616       0
28 -0.344169  0.818316       0
29  0.611894  0.801975       0
30 -0.730111 -0.860567       0
31 -0.779761  0.345376       0
32  0.745392 -0.306324       0
33 -1.101577 -0.081505       0
34  1.272028  0.674565       0
35  0.122584  0.289277       0
36 -1.681245 -1.518912       0
37 -1.201424 -0.945445       0
38  0.154020 -0.240710       0
39 -0.007465  1.038529       0

# PCA -- Class

In [150]:
class MyPCA:
  def __init__(self, n_components):

    """
    Parameter:
      n_components: int
        No. of compenents to keep.

    Attribute:
      components_: nd.array
        Contains component (eigenvectors) sorted by their importance (eigenvalues).

      explain_variance_ratio_: float
        Percatage of variance explain by n_components

      mean: float
        Mean of each feature.

      scale_: float
        Standard deviation of each feature.
    """

    self.n_components = n_components
    self.components_ = None
    self.explain_variance_ratio_ = None
    self.mean = None
    self.scale_ = None


  def fit(self, X):

    # Standardize the data
    self.mean = np.mean(X, axis= 0)
    self.scale_ = np.std(X, axis= 0)

    X_std = (X - self.mean) / self.scale_

    # Calulate Covariance Matrix
    cov_matrix = np.cov(X_std.T)

    # Find eigenvectors and eigenvalues
    eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

    # Sorting eigenvectors according to their values
    idx = np.argsort(eigen_values)[::-1]
    sorted_eigen_values = eigen_values[idx]
    sorted_eigen_vectors = eigen_vectors[:, idx]

    # Selecting n_components from sorted_eigen_vectors
    self.components_ = sorted_eigen_vectors[:, :self.n_components]

    # Total Variance
    total_variance = np.sum(eigen_values)

    # Variance explained by n_components
    self.explain_variance_ratio_ = sorted_eigen_values[: self.n_components] / total_variance

    return self

  def transform(self, X):

    if self.components_ is None:
      raise RuntimeError("You must call fit() before you can transform the data.")

    X_std = (X - self.mean) / self.scale_

    X_projected = np.dot(X_std, self.components_)

    return X_projected

  def fit_transform(self, X):

    self.fit(X)

    return self.transform(X)

In [158]:
X = df.iloc[:, 0:3]

In [159]:
pca_object = MyPCA(2)

In [162]:
pca_object.fit(X)

In [164]:
X_projected = pca_object.transform(X)

In [165]:
X_projected

array([[-0.50968719, -1.30862581],
       [-0.61628531, -0.5570411 ],
       [-0.07255535, -0.68176211],
       [ 2.04225567,  1.78828845],
       [-1.62486872,  1.06851585],
       [ 1.3295146 , -0.81643222],
       [ 1.2727929 ,  0.6890199 ],
       [-0.75418317,  0.50662746],
       [ 0.85668431,  1.06160675],
       [ 0.5552593 , -0.33579431],
       [ 0.04782138,  0.47637239],
       [-1.71234914,  0.7570209 ],
       [ 0.52233496, -0.06862451],
       [-0.80591188,  0.23979106],
       [-0.27939533,  2.45383231],
       [-1.75283221, -1.14505065],
       [ 0.74951828, -0.60962304],
       [ 1.79895357, -0.22942708],
       [ 0.63518695, -1.76875562],
       [ 0.06737388, -0.22493011],
       [ 0.16329633, -0.07223131],
       [ 0.83462402,  1.00827885],
       [-2.57193822,  0.11851702],
       [-0.1785907 , -0.97884896],
       [-0.13257779,  0.31405178],
       [ 1.93721102,  1.9105738 ],
       [ 1.12478703, -0.78286937],
       [-0.67167872, -0.52138402],
       [ 0.00263915,